apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-couchdb
spec:
    capacity:
        storage: 100M
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: "/tmp/couchdb"
