kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: pvc-couchdb
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10M
    storageClassName: ""
